# Assignment: Read a File into Python

Hi there,

I hear you’re the new junior data scientist on the team. Welcome!

Our polling partners just finished collecting survey data on the happiness levels in each country. I’ve attached the file.

Can you load the data into Python and confirm the number of rows in the data and the range of the happiness scores? Then we can walk through next steps together.

Thanks!\
Anna

*Attachment: happiness_survey_data.csv*

### 1. Read in data from a csv file

In [1]:
import numpy as np
import pandas as pd

In [20]:
happiness = pd.read_csv('../Data/happiness_survey_data.csv')

### 2. Store data in a DataFrame

In [21]:
happiness = pd.read_csv('../Data/happiness_survey_data.csv')

In [22]:
happiness

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Afghanistan,2008,3.723590,0.450662,0.718114,50.500000
1,Afghanistan,2009,4.401778,0.552308,0.678896,50.799999
2,Afghanistan,2010,4.758381,0.539075,0.600127,51.099998
3,Afghanistan,2011,3.831719,0.521104,0.495901,51.400002
4,Afghanistan,2012,3.782938,0.520637,0.530935,51.700001
...,...,...,...,...,...,...
2084,Zimbabwe,2017,3.638300,0.754147,0.752826,52.150002
2085,Zimbabwe,2018,3.616480,0.775388,0.762675,52.625000
2086,Zimbabwe,2019,2.693523,0.759162,0.631908,53.099998
2087,Zimbabwe,2020,3.159802,0.717243,0.643303,53.575001
2088,Zimbabwe,2021,3.154578,0.685151,0.667636,54.049999

### 3. Quickly explore the data in the DataFrame

In [23]:
happiness.info()

<class 'pandas.DataFrame'>
RangeIndex: 2089 entries, 0 to 2088
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   country_name                      2089 non-null   str
 1   year                              2089 non-null   int64
 2   happiness_score                   2089 non-null   float64
 3   social_support                    2076 non-null   float64
 4   freedom_to_make_life_choices      2057 non-null   float64
 5   healthy_life_expectancy_at_birth  2031 non-null   float64
dtypes: float64(4), int64(1), str(1)
memory usage: 98.1 KB

In [24]:
happiness.describe()

,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
count,2089.000000,2089.000000,2076.000000,2057.000000,2031.000000
mean,2013.727621,5.473747,0.811542,0.745462,63.180326
std,4.455614,1.115567,0.118935,0.140751,6.948546
min,2005.000000,2.178809,0.290184,0.257534,6.720000
25%,2010.000000,4.651972,0.747664,0.651689,58.965000
50%,2014.000000,5.405246,0.834770,0.767357,64.980003
75%,2017.000000,6.294282,0.904682,0.857677,68.362499
max,2021.000000,8.018934,0.987343,0.985178,74.349998

In [25]:
happiness.shape

(2089, 6)

In [26]:
happiness.dtypes

country_name                            str
year                                  int64
happiness_score                     float64
social_support                      float64
freedom_to_make_life_choices        float64
healthy_life_expectancy_at_birth    float64
dtype: object

In [28]:
run_times = pd.read_excel("../Data/Run Times.xlsx")

In [29]:
run_times

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

In [30]:
run_times.dtypes

Name                       str
Run Time               float64
Warm Up Time            object
Location                   str
Run Date        datetime64[us]
Race Date       datetime64[us]
Rain                      bool
Fee                        str
dtype: object

In [31]:
run_times.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          5 non-null      str
 1   Run Time      5 non-null      float64
 2   Warm Up Time  5 non-null      object
 3   Location      5 non-null      str
 4   Run Date      5 non-null      datetime64[us]
 5   Race Date     5 non-null      datetime64[us]
 6   Rain          5 non-null      bool
 7   Fee           5 non-null      str
dtypes: bool(1), datetime64[us](2), float64(1), object(1), str(3)
memory usage: 417.0+ bytes

In [32]:
df = run_times.copy()

In [34]:
clean_fee = df.Fee.str.replace("$","").str.replace(",","")

In [38]:
df.Fee = pd.to_numeric(clean_fee)

In [40]:
df.Fee

0    0.0
1    0.0
2    2.5
3    0.0
4    2.5
Name: Fee, dtype: float64

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          5 non-null      str
 1   Run Time      5 non-null      float64
 2   Warm Up Time  5 non-null      object
 3   Location      5 non-null      str
 4   Run Date      5 non-null      datetime64[us]
 5   Race Date     5 non-null      datetime64[us]
 6   Rain          5 non-null      bool
 7   Fee           5 non-null      float64
dtypes: bool(1), datetime64[us](2), float64(2), object(1), str(2)
memory usage: 417.0+ bytes

In [54]:
clean_time = pd.to_numeric(df['Warm Up Time'],errors='coerce')

In [55]:
clean_time

0    3.5
1    3.5
2    NaN
3    2.2
4    2.0
Name: Warm Up Time, dtype: float64

In [77]:
clean_time = pd.to_numeric(df['Warm Up Time'].astype(str).str.replace(" min","", case = False))

In [78]:
clean_time

0    3.5
1    3.5
2    3.0
3    2.2
4    2.0
Name: Warm Up Time, dtype: float64

In [82]:
df['Warm Up Time'] = clean_time

In [83]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          5 non-null      str
 1   Run Time      5 non-null      float64
 2   Warm Up Time  5 non-null      float64
 3   Location      5 non-null      str
 4   Run Date      5 non-null      datetime64[us]
 5   Race Date     5 non-null      datetime64[us]
 6   Rain          5 non-null      bool
 7   Fee           5 non-null      float64
dtypes: bool(1), datetime64[us](2), float64(3), str(2)
memory usage: 417.0 bytes

In [85]:
df.head()

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,0.0
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,0.0
2,Alexis,8.1209,3.0,“the gym”,2023-05-10 15:00:00,2023-06-01,False,2.5
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,0.0
4,David,6.8342,2.0,“gym”,2023-05-10 16:30:00,2023-06-15,False,2.5

In [89]:
df.Rain = df.Rain.astype(int)

In [90]:
df

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,0,0.0
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,1,0.0
2,Alexis,8.1209,3.0,“the gym”,2023-05-10 15:00:00,2023-06-01,0,2.5
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,0,0.0
4,David,6.8342,2.0,“gym”,2023-05-10 16:30:00,2023-06-15,0,2.5

In [171]:
alarm = pd.read_excel("../Data/Alarm Survey Data.xlsx")
alarm.info()

<class 'pandas.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   survey_id           6433 non-null   int64
 1   age                 6433 non-null   int64
 2   number_of_children  6433 non-null   float64
 3   activity_level      6433 non-null   str
 4   sleep_quality       6082 non-null   float64
 5   number_of_snoozes   6433 non-null   int64
 6   alarm_rating        6433 non-null   str
dtypes: float64(2), int64(3), str(2)
memory usage: 351.9 KB

In [172]:
alarm

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
0,1,34,3.0,active,3.0,1,5 stars
1,2,31,3.0,light,3.0,3,3 stars
2,3,18,0.0,light_activity,4.0,1,1 stars
3,4,42,4.0,active,4.0,1,4 stars
4,5,30,1.0,light_activity,1.0,4,3 stars
...,...,...,...,...,...,...,...
6428,6362,27,2.0,active,5.0,0,5 stars
6429,6363,31,1.0,light,4.0,0,4 stars
6430,6364,26,0.0,lightly active,5.0,0,3 stars
6431,6365,27,1.0,active,5.0,0,3 stars
6432,6366,18,0.0,lightly active,4.0,0,1 stars

In [173]:
# Columns to  be converted includes activity level, alarm_rating, they both are categorical data that need to be chot encoded into int numbers

In [174]:
alarm.alarm_rating = pd.to_numeric(alarm.alarm_rating.str.replace(" stars","",case = False))

In [175]:
alarm.info()

<class 'pandas.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   survey_id           6433 non-null   int64
 1   age                 6433 non-null   int64
 2   number_of_children  6433 non-null   float64
 3   activity_level      6433 non-null   str
 4   sleep_quality       6082 non-null   float64
 5   number_of_snoozes   6433 non-null   int64
 6   alarm_rating        6433 non-null   int64
dtypes: float64(2), int64(4), str(1)
memory usage: 351.9 KB

In [176]:
alarm.groupby('activity_level').describe()

               survey_id                                                  \
                   count         mean          std   min     25%     50%
activity_level
active            2450.0  3314.700000  1804.158162   1.0  1807.5  3349.5
light              334.0  2589.964072  1867.916219   2.0  1042.5  2114.5
light_activity     691.0  3021.017366  1857.109290   3.0  1578.5  2827.0
lightly active    2289.0  3081.095675  1891.970773   6.0  1438.0  3002.0
very active        669.0  3832.971599  1720.038760  18.0  2585.0  4040.0

                                   age             ... number_of_snoozes  \
                   75%     max   count       mean  ...               75%
activity_level                                     ...
active          4792.5  6365.0  2450.0  29.502857  ...               2.0
light           4042.0  6363.0   334.0  35.718563  ...               2.0
light_activity  4769.5  6323.0   691.0  23.794501  ...               2.0
lightly active  4757.0  6366.0  2289.0  28.610747  ...               2.0
very active     5198.0  6359.0   669.0  31.177877  ...               1.0

                     alarm_rating
                 max        count      mean       std  min  25%  50%  75%  max
activity_level
active           8.0       2450.0  2.955918  1.093662  1.0  2.0  3.0  4.0  5.0
light            6.0        334.0  3.308383  1.092201  2.0  2.0  3.0  4.0  5.0
light_activity  19.0        691.0  2.863965  1.161716  1.0  2.0  3.0  4.0  5.0
lightly active   6.0       2289.0  2.851900  1.051721  1.0  2.0  3.0  3.0  5.0
very active      7.0        669.0  3.222720  1.156739  1.0  2.0  3.0  4.0  5.0

[5 rows x 48 columns]

In [177]:
# alarm['activity_level'] = alarm['activity_level'].str.replace("light","0",case = False)

In [178]:
#alarm['activity_level'] = alarm['activity_level'].str.replace("light_activity","1",case = False)
#alarm['activity_level'] = alarm['activity_level'].str.replace("lightly active","1",case = False)
#alarm['activity_level']  = alarm['activity_level'].str.replace("light","0",case = False)
#alarm['activity_level'] = alarm['activity_level'].str.replace("active","2",case = False)
#alarm['activity_level'] = alarm['activity_level'].str.replace("very ","",case = False)

In [179]:
alarm['activity_level'] = (
    alarm.activity_level
    .str.strip()
    .str.lower()
    .replace({
        'light':1,
        'light_activity':2,
        'lightly active':2,
        'active':3,
        'very active':4,
    })
)

In [180]:

alarm['activity_level'] = pd.to_numeric(alarm['activity_level'])

In [181]:
alarm['activity_level'].head(50)

0     3
1     1
2     2
3     3
4     2
5     2
6     2
7     2
8     2
9     2
10    2
11    3
12    1
13    2
14    2
15    2
16    2
17    4
18    2
19    2
20    2
21    2
22    3
23    4
24    2
25    3
26    2
27    3
28    2
29    1
30    3
31    2
32    3
33    4
34    3
35    2
36    2
37    2
38    3
39    2
40    2
41    2
42    2
43    2
44    2
45    3
46    3
47    3
48    3
49    2
Name: activity_level, dtype: int64

In [190]:
alarm.sleep_quality = alarm.sleep_quality.fillna(alarm.sleep_quality.mode()[0]).head(50)

In [193]:
alarm.info()

<class 'pandas.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   survey_id           6433 non-null   int64
 1   age                 6433 non-null   int64
 2   number_of_children  6433 non-null   float64
 3   activity_level      6433 non-null   int64
 4   sleep_quality       50 non-null     float64
 5   number_of_snoozes   6433 non-null   int64
 6   alarm_rating        6433 non-null   int64
dtypes: float64(2), int64(5)
memory usage: 351.9 KB

In [194]:
alarm['activity_level'].info()

<class 'pandas.Series'>
RangeIndex: 6433 entries, 0 to 6432
Series name: activity_level
Non-Null Count  Dtype
--------------  -----
6433 non-null   int64
dtypes: int64(1)
memory usage: 50.4 KB