# Section 4: Gathering Data

## 1. Reading Flat Files

### a. The basics

In [3]:
import pandas as pd

In [5]:
pd.read_csv('../Data/course_offerings.csv')

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [ ]:
# Use shift-tab-tab-tab-tab (4 tabs) to view the arguments of pd.read_csv

### b. How to change the file location

In [ ]:
# If the file is in the same folder
pd.read_csv('course_offerings.csv')
pd.read_csv('/Users/alice/Desktop/Course_Materials/Data/course_offerings.csv')

In [2]:
# If the file is in another folder
pd.read_csv('../Data/course_offerings.csv')

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [ ]:
# If the file is one folder below
pd.read_csv('Data/course_offerings.csv')

### c. How to change the arguments

In [3]:
# Tweak the header argument
pd.read_csv('../Data/course_offerings.csv', header = None)

           0                            1             2
0  course_id                  course_name    instructor
1        101              Intro to Python  Chris Bruehl
2        102                 Intro to SQL   John Pauler
3        201    Exploratory Data Analysis    Alice Zhao
4        301                   Algorithms  Chris Bruehl
5        331  Natural Language Processing    Alice Zhao

In [4]:
# Tweak the sep argument
pd.read_csv('../Data/course_offerings.csv', sep = '|')

             course_id,course_name,instructor
0            101,Intro to Python,Chris Bruehl
1                102,Intro to SQL,John Pauler
2    201,Exploratory Data Analysis,Alice Zhao
3                 301,Algorithms,Chris Bruehl
4  331,Natural Language Processing,Alice Zhao

## 2. Reading Excel Files

In [11]:
# The basics
pd.read_excel('../Data/Course Offerings.xlsx')

     Instructor                    Title
0  Chris Bruehl   Lead Python Instructor
1   John Pauler     Chief Growth Officer
2    Alice Zhao  Data Science Instructor

In [6]:
# Tweak the sheet_name argument
pd.read_excel('../Data/Course Offerings.xlsx', sheet_name = 1)

   Course ID                  Course Name    Instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

## 3. Connecting to a SQL Database

In [12]:
# Connect to a SQLite database

import sqlite3
conn = sqlite3.connect('../Data/maven.db')

pd.read_sql('SELECT * FROM courses', conn)

   course_id                       course    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [13]:
# Another example of a SQL query
pd.read_sql('SELECT * FROM courses WHERE course_id LIKE "1%"', conn)

   course_id           course    instructor
0        101  Intro to Python  Chris Bruehl
1        102     Intro to SQL   John Pauler

In [15]:
# The setup for other software like MySQL, PostgreSQL,
# Oracle and SQL Server is more involved

# 1. Install a database driver (pip install or conda install)
!pip install mysql-connector-python

# 2. Set up the database connection
import mysql.connector
conn = mysql.connector.connect(host='localhost',
                               database='my_new_db',
                               user='alice',
                               password='password')

# 3. Write SQL code in Python
pd.read_sql('SELECT * FROM courses', conn)

Requirement already satisfied: mysql-connector-python in /Users/user/Documents/Laboratory/ai&ml/examples/notebooks/.venv/lib/python3.12/site-packages (26.7.0)

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (61)

## 4. Quickly Explore a DataFrame

In [16]:
# Save the output as a DataFrame

df = pd.read_csv('../Data/course_offerings.csv')
df

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [10]:
df.head(3)

   course_id                course_name    instructor
0        101            Intro to Python  Chris Bruehl
1        102               Intro to SQL   John Pauler
2        201  Exploratory Data Analysis    Alice Zhao

In [11]:
df.shape

(5, 3)

In [12]:
df.count()

course_id      5
course_name    5
instructor     5
dtype: int64

In [13]:
df.describe()

        course_id
count    5.000000
mean   207.200000
std    107.829495
min    101.000000
25%    102.000000
50%    201.000000
75%    301.000000
max    331.000000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   course_id    5 non-null      int64
 1   course_name  5 non-null      object
 2   instructor   5 non-null      object
dtypes: int64(1), object(2)
memory usage: 248.0+ bytes